### ISSUE TITLE
Feature Request: Software Interrupt Support for Pin Status Changes

### ISSUE THREAD

**Issue by firaskhf** [rsg98/homebridge-gpio-wpi2#1]
Hi it's a question not an issue, but i couldn't find another way to ask except here.
are you going to add Polling feature as well?
keep up the great work, and apology if my question is irrelevant. i'm new to all of this. 
regards,

**Comment by rsg98** [comment]
Could you describe what you'd like to see it do? (E.g. Is something else turning off the GPIO and you need to get homebridge to poll and update HomeKit, or is this related to the "duration" timer)?

**Comment by firaskhf** [comment]
As you said, I need to get homebridge to poll and update HomeKit.
I want to use a PIR Sensor as a GPIO input SENSOR, i want it to be detected immediately so that i can trigger another GPIO output.
note that i tried it with wpi1 (i configured PIR as GPIO input SWITCH)and it did not trigger unless i close and reopen the Home app, or swipe up/down in my iphone.
I was wondering if this also can help update 1 wire config sensors such as ds18b20, cause i also can't refresh the reading of that sensor unless i close and reopen, which makes me unable to create a scene to trigger a GPIO output, if ds1818b20 reaches certain temp.
Sorry again if i'm talking nonsense. My knowledge in programming is basic.
Thank you.

**Comment by rsg98** [comment]
Added a polling feature (homebridge-gpio-wpi2@0.0.8), but I'm also in the process of adding in the ISR support to node-wiring-pi (this means that we shouldn't need to poll the pins, we can register for an interrupt and have WiringPi tell us when the pin state has changed).

Will close this issue once interrupt driven GPIO INPUT support is added.

**Comment by firaskhf** [comment]
Adding interrupt is gooooood.
Keep up the great work.

**Comment by pedroserano** [comment]
I just wanted to say thank you for the great work. This plugin allowed me to install a PIR sensor, and I replaced the ContactSensor with a MotionSensor for the accessory type. If anyone is interested, the modified code is here - I only needed to modify index.js: https://github.com/pedroserano/homebridge-gpio-wpi2

I played briefly with trying to add a motion sensor as a third option - another kind of input besides a contact sensor - but ended up just replacing the contact sensor because it was easier.

**Comment by mv1993** [comment]
Hi, I've got a question: Is it possible to implement softPWM to this plugin? I want to control the brightness of a LED. 
Thank you

**Comment by rsg98** [comment]
softPWM should be easy enough - I'll track this as a separate issue (rsg98/homebridge-gpio-wpi2#7)

**Comment by justacec** [comment]
Earlier in this discussion you indicated you were going to add interrupt handling to the backend.  Have you added this.  I have looked at the code and a quick check did not seem to indicate you had.  I most likely overlooked it if you did.  Is this a feature yet?  If not, is there a timeline to get that added?

Wait.  I think that I see where you might have done it.  Confused by the filesystem / hardware interface with the polling.....
