### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by maciekish** [rsg98/homebridge-gpio-wpi2#11]
Where does the confg file go? I edited the sample and saved without sample suffix in filename and there are no accessories visible for Homebridge on iOS.

**Comment by rsg98** [comment]
The confit-platform-sample.json is an example of what needs to go inside your main homebridge confit.json (this plugin doesn't have a separate config file).

The homebridge README has some more detail on this:

https://github.com/nfarina/homebridge/blob/master/README.md

"NOTE: Your config.json file MUST be inside of .homebridge, which is inside of your home folder. On MacOS and Linux, the full path for your config.json would be ~/.homebridge/config.json. Any error messages will contain the exact path where your config is expected to be found."

(Unless you start homebridge with -C option, which lets you choose a different confit location)
