### ISSUE TITLE
Inversion doesnt seem to be working

### ISSUE THREAD

**Issue by maciekish** [rsg98/homebridge-gpio-wpi2#12]
Hi, i have GPIO pin 2 set with inverted to true but on still yields a 1 (3.3v) and off 0. I changed this after adding the accessory, do i have to readd it or something? I restrted homebridge after changing the config.

**Comment by maciekish** [comment]
Also with the config below i get the pin 2 twice in HomeKit, once as Anet A6 and once as GPIO2.

      GNU nano 2.2.6              File: /var/lib/homebridge/config.json                                    
                                                                                                       
{                                                                                                      
    "bridge": {                                                                                        
        "name": "Anet Homebridge",                                                                     
        "username": "CC:22:3D:E3:CE:30",                                                               
        "port": 51826,                                                                                 
        "pin": "198-61-986"                                                                            
    },                                                                                                 
                                                                                                       
    "description": "Homebridge running on Anet A6 Raspberry Pi.",                                      
                                                                                                       
    "platforms": [                                                                                     
    {                                                                                                  
        "platform" : "WiringPiPlatform",                                                               
        "name" : "Pi GPIO (WiringPi)",                                                                 
        "overrideCache" : "false",                                                                     
        "autoExport" : "true",                                                                         
        "gpiopins" : [{                                                                                
            "name" : "Anet A6",                                                                        
            "pin"  : 2,                                                                                
            "enabled" : "true",                                                                        
            "mode" : "out",                                                                            
            "pull" : "down",                                                                           
            "inverted" : "true",                                                                       
            "duration" : 0,                                                                            
            "polling" : "true"                                                                         
        }]                                                                                             
    }]                                                                                                 
}

**Comment by rsg98** [comment]
I think both of these issues are related... 

The following translations from HomeKit speak might help with the following:
- **Platform** = e.g. this plugin (specifically, plugins using homebridge API 2.0)
- **Accessory** = each GPIO pin
- **Service** = the HomeKit services attached to each pin (e.g. switch, contact sensor)
- **Characteristic** = what each service can do (e.g. On/Off)

Homebridge caches accessories in ``accessories/cachedAccessories`` - which is just a JSON file.  This file stores all the accessories (GPIO pins) and services (e.g. contact sensor, switch) associated with each pin.

Plugins (using API 2.0, like ``homebridge-gpio-wpi2``) read the information back from this cache at startup.  That includes the ``inverted`` and ``duration`` settings, for example.

If a pin configuration is missing from the cache, the plugin will load the configuration from ``config.json`` once all cached accessories have been loaded.  This cache is keyed around the name (footnote 1) of the accessory (gpio pin) - so if you change the name in ``config.json``, homebridge sees it as a 'new' accessory (hence your duplicates).

If you set ``"overrideCache" : "true"`` at the platform level, ``homebridge-gpio-wpi2`` will ignore those settings in the cache and overwrite them with the ones from your ``config.json``.  I'm guessing this is why it's ignoring your ``inverted`` setting.

The ``overrideCache`` setting currently does **not** fix:
- Duplicates - if you change the name in the config
- Mode changes - mode changes implies a change in the Services attached to the accessory - the plugin doesn't currently update the services

You can rename accessories in the Home app - which is preferable to renaming them in ``config.json`` - as it means all scenes, etc. will follow the accessory.

While you are experimenting / setting up the plugin, it's probably helpful to leave ``overrideCache`` set to ``true``.  If you rename pins or change modes, then you can delete ``accessories/cachedAccessories`` and restart ``homebridge``.  (Note that this cache is a ``homebridge`` cache - no specific to this plugin - so it will remove the cache from any other plugins you have installed as well!)


1.  It's not the name itself, it's a UUID derived from the name - but a given name always returns the same UUID, so they are effectively keying around the name.

**Comment by maciekish** [comment]
Took me a while to figure out that `homebridge` writes the `cachedAccessories` on shutdown so deleting it before restarting `homebridge` didn't do much. Thanks a lot for your time!
