### ISSUE TITLE
Package not on npm registry

### ISSUE THREAD

**Issue by aminemami** [rsg98/homebridge-gpio-wpi2#2]
I'm getting an error when trying to install this:

sudo npm install -g homebridge-gpio-wpi2

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/homebridge-gpio-wpi2
npm ERR! 404 
npm ERR! 404  'homebridge-gpio-wpi2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by rsg98** [comment]
I haven't finished writing the module yet (it doesn't actually do much at present!)

Will publish to NPM and close this issue as soon as it's ready.

**Comment by rsg98** [comment]
Version 0.0.8 published... (not tested all aspects yet though!)
