### ISSUE TITLE
makes homebridge and the accesories unresponsive

### ISSUE THREAD

**Issue by RGinguls** [rsg98/homebridge-gpio-wpi2#26]
Adding this plugin made the accessories appear in Home app, but now homebridge and accessories appear with "No Response"

**Comment by rsg98** [comment]
Is homebridge still running or has it crashed? There should be logs if you
run it in a console...

**Comment by RGinguls** [comment]
Still running, thats the worst part, nothing to debug

**Comment by rsg98** [comment]
There's some debug flags you can add that might help - see the nearly
hidden top line of
https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting

**Comment by RGinguls** [comment]
Tried all that, no debug info on whats happening, and if remove my unresponsive homebridge from Home app, the app cannot find it anymore, but the process is indeed running on RPi

**Comment by RGinguls** [comment]
Searched some more, don't know why this happened after I added this plugin, but i disabled the IPv6 in RPi and my iPhone was on 5GHz channel on my router and RPi was on 2.4Ghz, when I switched iPhone to 2.4GHz everything worked, it all now works perfectly, reporting status and toggle is working, thanks for setting me on the right way, and for such a quick response
