### ISSUE TITLE
error

### ISSUE THREAD

**Issue by firaskhf** [rsg98/homebridge-gpio-wpi2#3]
1. i'm getting this warning while installing:
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/.node-gyp"

2. after installing and configuring the pins, the mode in/out is not responding. Do i have to add "make-gpio-script" for the gpio pins to work if yes how?

Thank you,

**Comment by rsg98** [comment]
If you update your version of the module to 0.1.0, I've added an autoExport option - see the README for more details, but basically:

1.    Check your homebridge user is in the gpio group
2.    Add `"autoExport" : "true"` to the platforms section of your config file

This removes the need to run any `make-gpio-script` or `set-gpio.sh` before starting Homebridge.

This works on the Raspbian Jessie image I have, where the group `gpio` has access to `/sys/class/gpio`.  If it doesn't work on your OS, then the `make-gpio-script` is still there:

```
node make-gpio-script config.json set-gpio.sh
```

...which will generate a `set-gpio.sh` script which you can run as (for example) an `ExecStartPre` command in `systemd`.  (But, hopefully, you can ignore all this by using `autoExport` instead!)
