### ISSUE TITLE
Removing gpio pins from homebridge

### ISSUE THREAD

**Issue by Uweklaus** [rsg98/homebridge-gpio-wpi2#35]
Hi I am very new to homebridge and home automation. 
Now I am experimenting on my Pi3 with this and was able to use RCswitch successfully with my plugs and integration into homekit. 
Now I am experimenting with the GPIO, because I want to trigger the switches of a remote, which is not compatible to RCswitch. 
One problem was already addressed in another Issue (trigger gpio: lamp on, trigger a second time: lamp off), where was stated that this is currently not possible to solve. ok - I will find another way.

My question is how to remove the GPIO Pins (switches) from the homebridge.
If I remove them from the config file, they are still there in the homekit. homebridge runs with warnings.
If I rename them (eg. GPIO2 to Button 1) the homebridge stops with an error, that it can not handle this. 
I tried to clear the cache, but not sure whether it worked, because there was no change in the behaviour.

I would be thankful for any hint to a newbee in this.

**Comment by firaskhf** [comment]
You have to stop homebridge, delete everything in cachedAccessories file, then start homebridge again.
you can find cachedAccessories file in .homebridge/accessories

**Comment by Uweklaus** [comment]
Thanks, I will try this. Maybe not stopping homebridge before clearing was the point.

**Comment by Uweklaus** [comment]
Worked

**Comment by IgorGepich** [comment]
Thanks!
