### ISSUE TITLE
on homebridge boot set initial state of gpio to on or off state: feature request

### ISSUE THREAD

**Issue by pponce** [rsg98/homebridge-gpio-wpi2#4]
I recently installed this plugin once i saw that gpi-wpi was deprecated.
I have everything working but had one small issue/request.
My GPIO pins are inverted.  I've set the inverted config value to true and on off works as expected.
My issue is that when homebridge first "boots" up my lights that are controlled by the GPIO pins are turned on.  I'd like them to remember last state if possible (stay on or off based on last state) but if not possible would be great to have them be in the off state on initial homebridge startup.

**Comment by rsg98** [comment]
I think last state would be overwritten by WiringPi setup (although that's a guess!) - and most of the time, we're restarting Homebridge as part of a Pi reboot (so there is no last state).  Inverting the default value for inverted pins makes sense though.

**Comment by pponce** [comment]
thanks for the fast turn around. Will update tonight.

**Comment by AnakinCzar** [comment]
Mine does the same as well . When I first had “Invereted” set to FALSE , my lights would turn on as soon as I start Homebridge and stay on until I tell Siri to turn off  . Now that I changed “Inverted” to TRUE, my lights turn on for 1 second and then quickly turn off and stay off until I tell Siri to turn on . Any specific way I gotta have my code ?
