### ISSUE TITLE
The plugin doesn't find the config

### ISSUE THREAD

**Issue by Jabada90** [rsg98/homebridge-gpio-wpi2#5]
I installed the plugin and made sure the home bridge user has access to the group gpio. I configured the config.json, but Homebridge always crashes and displays"ERROR LOADING PLUGIN homebridge-gpio-wpi2:
[1/28/2017, 6:25:21 PM] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/compiled/4.3.2/linux/arm/nodeWiringPi.node
    at bindings (/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/index.js:1:99)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-wpi2/index.js:1:75)
    at Module._compile (module.js:409:26)"
and:
"/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'WiringPiPlatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3"

**Comment by apt222** [comment]
sudo npm install -g homebridge-gpio-wpi2

**Comment by rsg98** [comment]
Looks like node-wiring-pi (one of the plugin dependencies) didn't install properly.

Do you have an install.log file in /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/

If so, that should tell you why it failed.

**Comment by Jabada90** [comment]
Yes, a log is there. It says:
Package: wiringpi
Status: install ok installed
Priority: optional
Section: libraries
Maintainer: Gordon Henderson <projects@drogon.net>
Architecture: armhf
Version: 2.32
Depends: libc6
Description: The wiringPi libraries, headers and gpio command
  Libraries to allow GPIO access on a Raspberry Pi from C and C++
  programs as well as from the command-line
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build'
  CXX(target) Release/obj.target/nodeWiringPi/src/addon.o
  CXX(target) Release/obj.target/nodeWiringPi/src/wiringPi.o
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../src/addon.h:10,
                 from ../src/wiringPi.h:5,
                 from ../src/wiringPi.cc:1:
../src/wiringPi.cc: In function ‘void nodewpi::init_wiringPi(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/wiringPi.cc:701:32: error: ‘PI_MAKER_MBEST’ was not declared in this scope
   NODE_DEFINE_CONSTANT(target, PI_MAKER_MBEST);
                                ^
/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/.node-gyp/4.3.2/include/node/node.h:227:54: note: in definition of macro ‘NODE_DEFINE_CONSTANT’
         v8::Number::New(isolate, static_cast<double>(constant));              \
                                                      ^
nodeWiringPi.target.mk:104: recipe for target 'Release/obj.target/nodeWiringPi/src/wiringPi.o' failed
make: *** [Release/obj.target/nodeWiringPi/src/wiringPi.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

Can anybody tell me what went wrong with the install-process? Im a little bit confused because I've bought a new raspberry pi 3 and I constantly get this error whereas on my old pi 2, I installed it once and it worked right away.

**Comment by rsg98** [comment]
It's a bug in node-wiring-pi - I'll fix in and push an updated version to npm.

**Comment by pponce** [comment]
I'm getting this same error now that i've updated to this latest version with this fix.
"ERROR LOADING PLUGIN homebridge-gpio-wpi2:
 Error: Could not locate the bindings file. Tried:
I was not getting this error before...

**Comment by pponce** [comment]
uninstalling 0.1.2 and re-installing 0.1.1 fixed the issue for me

**Comment by pponce** [comment]
not sure if i'm doing something wrong. Whey i try to update to latest version 0.1.3 i'm not able to.
tried 
npm install -g homebridge-gpio-wpi2
That installed 0.1.2
npm install -g homebridge-gpio-wpi2@0.1.3
didn't work.
Does it take a bit longer for things to propagate?

**Comment by rsg98** [comment]
More that I forgot to publish it :)

It's appearing on npmjs.com now - so hopefully will work if you ``npm -g update``

One thing to note: if you upgrade your wiring pi package using ``apt-get update; apt-get upgrade`` or similar, then ``node-wiring-pi`` may need to be rebuilt with ``node-gyp rebuild`` (or just reinstalling the module)

**Comment by pponce** [comment]
ok. i see them now. :)
No issues installing and running homebridge now with latest versions of this plug in.

**Comment by maciekish** [comment]
I'm hitting this issue as well! I tried @0.1.3 and had the same issue.

    ****@****:~ $ sudo npm install -g homebridge-gpio-wpi2
    /opt/nodejs/lib
    └── homebridge-gpio-wpi2@0.2.0

**Comment by rsg98** [comment]
Can you post your install.log (see earlier comment for likely locations)

**Comment by maciekish** [comment]
I tried with the --unsafe-perm option as well to get rid of the root warning, same issue.

Package: wiringpi
Status: install ok installed
Priority: optional
Section: libraries
Maintainer: Gordon Henderson <projects@drogon.net>
Architecture: armhf
Version: 2.32
Depends: libc6
Description: The wiringPi libraries, headers and gpio command
  Libraries to allow GPIO access on a Raspberry Pi from C and C++
  programs as well as from the command-line
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/nodejs/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/.node-gyp"
make: Entering directory '/opt/nodejs/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build'
  CXX(target) Release/obj.target/nodeWiringPi/src/addon.o

**Comment by maciekish** [comment]
Nevermind, i uninstalled homebridge-gpio-wpi2 and reinstalled it once more and now it works.. Magic..

**Comment by Kepete** [comment]
I have the same exact error as the publisher. I can't figure out what's going on: 
If I try `sudo npm install -g homebridge-gpio-wpi2@0.1.3` I get: 

<img width="491" alt="screen shot 2018-01-24 at 20 00 14" src="https://user-images.githubusercontent.com/32489848/35348701-7d59daae-0141-11e8-96b1-310f078c3b77.png">

When I try `sudo npm install -g homebridge-gpio-wpi2` I get this error: 

<img width="1134" alt="screen shot 2018-01-24 at 20 03 43" src="https://user-images.githubusercontent.com/32489848/35348768-b64b16de-0141-11e8-9533-ca0922f830a7.png">

And the main problem is this error when I run Homebridge: 

<img width="1280" alt="screen shot 2018-01-24 at 19 23 52" src="https://user-images.githubusercontent.com/32489848/35348809-d7c43084-0141-11e8-9463-bd8ac94ef2ba.png">

**Comment by StefanMeGit** [comment]
Exactly the same for me... I can not install this plugin
