### ISSUE TITLE
Compile Error against node v10.12.0

### ISSUE THREAD

**Issue by ingski** [rsg98/homebridge-gpio-wpi2#54]
Hi,

due to some other home bridge modules requirement for a newer node version I installed the latest one today.
Unfortunately the nom install for homebridge-gpio-wpi2 fails due to a compile error:

make: Verzeichnis „/usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/epoll/build“ wird betreten
  CXX(target) Release/obj.target/epoll/src/epoll.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/epoll.cc:15:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~

Do you see a chance for a fix other than switching back to an older version of node?

-
Ingo

**Comment by rsg98** [comment]
Ah - it needs an updated version of epoll in the package file - think the latest is 2.0.6 which it won’t match as the major semver is different. Will fix the package.json and republish.

**Comment by ingski** [comment]
Great. I'll check it once available. 

For now I'm using the "cmdSwitch2" module with a bunch of "pigs" commands on the command line as a workaround.

**Comment by pponce** [comment]
ran into this just today.
Is it as simple as changing this line below in package.json?
"epoll" : "^0.1.21"
to
"epoll" : "^2.0.6"

**Comment by rsg98** [comment]
Yes, should be.

**Comment by pponce** [comment]
Thanks,
I actually just found a fork by jvmahon with the updated changes to the package.json file.
Ran this and I was good to go
npm install -g jvmahon/homebridge-gpio-wpi2

**Comment by rsg98** [comment]
Fixed in ceb1993
